Front changes
mishalov/brno-games pull request #2
Opened 2023-01-21 11:50 UTC by Temich21

Здарова, должно вроде бы все работать

2023-01-22 20:17 UTC, Temich21 commented
Исправил то что ты говорил, добавил картинку на задний фон. Также добавил @media для устройств.

2023-01-23 19:58 UTC, Temich21 commented
Изменил html - добавил semantic

2023-01-23 22:06 UTC, mishalov requested changes

2023-01-23 22:06 UTC, mishalov commented on games-front/src/js/scripts.js
> +        element = titleAndTextAppend(
@Temich21 ты уверен что этот код работает? Я не вижу чтобы где-то объявлялась переменная `element`

2023-01-23 22:06 UTC, mishalov commented on games-front/src/js/scripts.js
> +        element = titleAndTextAppend(newElement, titleElement, textElement, data);
Тут тоже

2023-01-24 16:16 UTC, Temich21 commented on games-front/src/js/scripts.js
> +        element = titleAndTextAppend(
Да работает, но только там должен поидеи быть перед element const.

2023-01-24 16:37 UTC, Temich21 commented on games-front/src/js/scripts.js
> +        element = titleAndTextAppend(
добавил объявление element и исправил ссылку на телеграмм аккаунт, надо было вводить без @ вначале. Теперь когда кликаешь открывается сразу чат с аккаунтом.

2023-01-25 16:54 UTC, mishalov approved these changes

2023-01-25 16:54 UTC, merged